### PR TITLE
fix: exclude tags that are already selected in resource form ❗️

### LINKED ISSUE #273: Tag isn't excluded from search if already selected 🏷️

### PR DESCRIPTION
**Pull request by jessherlitz**
## Description ✏️

Closes #273 

Fixed the following bugs:
- when you select a tag, the tag will leave the popover.
- when you de-select a tag, tag repopulates popover.
- when you create a tag, tag is automatically selected.

## Type of Change 🐞

- [ ] Feature - A non-breaking change which adds functionality.
- [x] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

File: apps/member-profile/app/shared/components/resource-form.tsx [hunk 1]
```diff
@@ -136,20 +136,75 @@ export function ResourceTagsField({
...
   useEffect(() => {
     listFetcher.load('/api/tags/search');
   }, []);
 
   const tags = listFetcher.data?.tags || [];
 
-  function reset() {
+  function onTagCreated(newTag: unknown) {
+    createFetcher.submit(
+      { id: newTag.id, name: newTag.label },
```
Comment (tomas-salgado) [inline apps/member-profile/app/shared/components/resource-form.tsx:150]: I think there may be some type-related issues here because since the newTag type is unknown, the compiler doesn't know if newTag has the attributes of "id" and "label". It seems this wasn't an issue before because in the simpler uses of `tag`, the structure of `tag` was still more explicit and hence could be inferred by the compiler. 

I'm curious if it'd be worth defining a type called "Tag" so that `newTag` and `tag` can have more explicit types. This could be done as follows: 
```
interface Tag {
  id: string;
  name: string;
}
```

File: apps/member-profile/app/shared/components/resource-form.tsx [hunk 2]
```diff
@@ -136,20 +136,75 @@ export function ResourceTagsField({
...
+        method: 'post',
+      }
+    );
     setSearch('');
-    setNewTagId(id());
+    setSelectedTags({ ...selectedTags, [newTag.id]: newTag });
+    listFetcher.load('/api/tags/search');
   }
 
+  const onTagSelected = (tag: unknown) => {
```
Comment (tomas-salgado) [inline apps/member-profile/app/shared/components/resource-form.tsx:161]: As mentioned earlier, if we define a type `Tag`, then we could replace `(tag: unknown)` with `(tag: Tag)`.

Comment (jessherlitz) [reply apps/member-profile/app/shared/components/resource-form.tsx:161]: Thank you Tomas! I am working on it.

**Review by ramiAbdou — APPROVED** [review]
Thank you so much for your work here, @jessherlitz! 🚀

I used your approach to keep track of the selected values in order to filter out the already selected tags, and I just moved some of that logic to the `MultiCombobox` since we technically already have that state tracked there! Thank you for inspiring this change because now we'll be able to easily filter out already selected values whenever we use the `MultiCombobox` component! 🎉
