### PR TITLE
fix: add check to stop incorrect rejection emails 🔎

### LINKED ISSUE #93: Rejection email is sent after being accepted 😕
### Description

A bit of context: we have a job that runs about 2.5 minutes after an application is received and it's responsibility is to reject a member if possible (ie: wrong graduation year, email bounced, etc).

There's an edge case where if an application is accepted within 2.5 minutes, but the job that runs after wants to reject them, it will and it will also send a rejection email (despite that the member was accepted and already invited to the community).

### Steps to Reproduce

1. Apply to the ColorStack with a bad graduation year (ie: 2023).
2. Within 2.5 minutes, accept the application in the Admin Dashboard.
3. After that 2.5 minutes has elapsed, you will get a rejection email.

### Expected Behavior

After an application is accepted, they should not get a rejected email.

### Additional Context

The [`reviewApplication`](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/application/use-cases/review-application.ts#L9) function is the one responsible for auto-rejections. We should modify this so that we only look at functions where the `status` is `pending`.

### PR DESCRIPTION
**Pull request by Boris713**
## Description ✏️

Closes #93 

A bit of context: we have a job that runs about 2.5 minutes after an application is received and it's responsibility is to reject a member if possible (ie: wrong graduation year, email bounced, etc).

- Added check that filters only applications where status = pending in database
- This will stop applications in either accepted or rejected from receiving auto reject emails

## Type of Change 🐞

- [ ] Feature - A non-breaking change which adds functionality.
- [x] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

File: packages/core/src/modules/application/use-cases/review-application.ts [hunk 1]
```diff
@@ -24,6 +24,7 @@ export async function reviewApplication({
       'applications.schoolId',
     ])
     .where('id', '=', applicationId)
+    .where('status', '=', ApplicationStatus.PENDING)
     .executeTakeFirstOrThrow();
```
Comment (ramiAbdou) [inline packages/core/src/modules/application/use-cases/review-application.ts:29]: Previously we'd throw an error if the application wasn't found. But now that we're also checking for the pending status, I don't think we should throw an error per se since we know about this case now.

Let's use `.executeTakeFirst` instead of `.executeTakeFirstOrThrow` and just return early if the application isn't found, ie:

```
if (!application) {
  return;
}
```

**Review by ramiAbdou — CHANGES_REQUESTED** [review]
Thanks for this update, @Boris713! Just one small change and it'll be good to ship!

File: packages/core/src/modules/application/use-cases/review-application.ts (hunk 1 above)
Comment (ramiAbdou) [reply packages/core/src/modules/application/use-cases/review-application.ts]: I'm going to bring this home - just updated!

**Review by ramiAbdou — APPROVED** [review]
