### PR TITLE
fix: reset search after creating resource tag 🏷️

### LINKED ISSUE #272: Search isn't reset after creating resource tag 🔎
### Description

After creating a tag for a resource, the dropdown that is supposed to show all available tags is only showing the tag that just got created because the search value is not being reset under the hood (though in the UI it seems to be reset).

### Steps to Reproduce

1. Go to `/resources/add` to add a resource.
2. Create/select a new tag.
3. The newly created tag is the only one that appears in the dropdown.

### Expected Behavior

After creating a tag, the search should truly reset and the dropdown should show all options as if there was an empty search value.

### Screenshots

https://github.com/colorstackorg/oyster/assets/38056800/6997b16c-8e7f-434d-8267-9391f8ef5dd8

### Additional Context

A good place to start with this is the [`ResourceTagsField`](https://github.com/colorstackorg/oyster/blob/ba2e91c5d27303f3b5414ec79ef154806c8218d1/apps/member-profile/app/shared/components/resource-form.tsx#L131).

### PR DESCRIPTION
**Pull request by iperalta7**
## Description ✏️

Closes #272

Describe what this PR does.

- Modifies `reset()` to call and reset the tag list with `listFetcher.submit()` to ensure the list of available tags shows when a new tag is created. 
- See issue to see the bug, the following video shows how it changed: 

https://github.com/user-attachments/assets/85707ad4-ffdd-4cf8-9264-bbbbdabe7c88

## Type of Change 🐞

- [ ] Feature - A non-breaking change which adds functionality.
- [x] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).
- [x] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by iperalta7** [comment]
Will add a quick video later today to showcase this, but can easily be seen in local environment

File: apps/member-profile/app/shared/components/resource-form.tsx [hunk 1]
```diff
@@ -158,6 +158,13 @@ export function ResourceTagsField({
   function reset() {
     setSearch('');
     setNewTagId(id());
+    listFetcher.submit(
+      { search: '' },
+      {
+        action: '/api/tags/search',
+        method: 'get',
+      }
+    );
```
Comment (tomas-salgado) [inline apps/member-profile/app/shared/components/resource-form.tsx:167]: I like this solution! It's simple and resolves the bug. I do wonder if we can optimize further since we are passing in an empty string as the search parameter. Maybe we can replace this with a simpler 
```    
listFetcher.load('/api/tags/search');
```
which will default to a GET method with an empty string.

Comment (iperalta7) [reply apps/member-profile/app/shared/components/resource-form.tsx:167]: Thanks! Let's try that out. I was messing around with this, goes to show I am a react newbie 🤭

**Review by tomas-salgado — APPROVED** [review]
LGTM! 🛫

**Review by ramiAbdou — APPROVED** [review]
Thanks for the work here @iperalta7! 🚀

I made a slight tweak which updated the functionality for all `MultiCombobox`'s that are used throughout our applications, b/c this was actually a bit more of an underlying issue with that component than just the `ResourceTagsField` (though your solution fixed that piece perfectly). The crux of the issue is that the `onChange` handler wasn't getting trigger in the `MultiComboboxSearch`, but was able to find a workaround for that.

Thanks again man!
