### PR TITLE
fix: dropdown formatting fix 🗄️ 

### LINKED ISSUE #191: Dropdown element has inconsistent positioning 🐞
### Description

The `Dropdown` element gives inconsistent placement, and sometimes gets pushed off the screen. 

### Steps to Reproduce

This issue can be seen in on the `Students` page of the admin-dashboard. 
Screenshot 2024-05-01 at 11 18 01 AM

This was also noticed while working on #184, as when creating a new dropdown for rejected applications, the default formatting for the `Dropdown` resulted in the following: 
Screenshot 2024-05-01 at 11 17 11 AM

### Expected Behavior

We want the `Dropdown` element to have consistent positioning that places it in-line with the table it is associated with. Right now it seems that the x-axis positioning is dependent on the width and number of fields within the table. However, since the table width is always fixed, this results in the weird positioning. 

### Additional Context

This change should just require modifying the way the Tailwind CSS is implemented for `Table.Dropdown` [here.](https://github.com/colorstackorg/oyster/blob/061c304f3173b9daefe1c78802b7186b72a3767d/packages/ui/src/components/table.tsx#L184) Note that making modifications there will change the formatting of all instances of `Dropdown` found in the app.

### PR DESCRIPTION
**Pull request by tomas-salgado**
## Description ✏️

Closes #191 

This PR adds a right margin to the `Dropdown` element so that the positioning is consistent and not pushed off the main window. 

Before: 
Screenshot 2024-05-08 at 11 35 02 AM
After: 
Screenshot 2024-05-08 at 11 37 39 AM

Before:
Screenshot 2024-05-08 at 11 36 23 AM
After: 
Screenshot 2024-05-08 at 11 36 50 AM

## Type of Change 🐞

- [ ] Feature - A non-breaking change which adds functionality.
- [x] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

File: packages/ui/src/components/table.tsx [hunk 1]
```diff
@@ -181,7 +181,7 @@ function TableBody({
 
 Table.Dropdown = function TableDropdown({ children }: PropsWithChildren) {
   return (
-    <Dropdown className="fixed right-[unset] mt-[unset] translate-x-[calc(-100%-0.5rem)]">
+    <Dropdown className="fixed mr-4 translate-x-[calc(-0.5rem)]">
```
Comment (ramiAbdou) [inline packages/ui/src/components/table.tsx:184]: So this is definitely better than the existing solution (and will be happy to merge), but not quite "the" solution that works in all cases.

This will only work when the table extends to a very specific of 16px to the left of the right edge of the page. That's because of the `right: 0` position, which is the default in `Dropdown`. The reason I'm okay with merging is b/c all tables right now extend to that `16px` point .

The idea I was going for before was unsetting the right position, which means that it'll automatically inherit the right position from its parent, but the reason it doesn't seem to be working is because when the table row is scrollable, the actual right position includes the scroll position, and thus it's pushed to the right of the screen.

If you can come up with a solution (ideally without Javascript) that works in a less hard-codey-ish way, that would be ideal but if not I'll merge it!

---

Also, nit but let's keep that `mt-[unset]`, I like the look of the dropdown being aligned to the top of the 3-dot button!

Comment (tomas-salgado) [reply packages/ui/src/components/table.tsx:184]: Ah, I see your point. I've been playing around with different options, and when using `absolute right-[unset]` instead of `fixed right-[unset]`, the positioning is all great, except there's the big issue that when there are multiple dropdown elements, they are getting hidden and you have to scroll down to see them. 
Screenshot 2024-05-09 at 9 08 39 AM
Screenshot 2024-05-09 at 9 09 10 AM
This makes me think that if we want to confine the x-axis of the dropdown to auto-align with the table width (by using `absolute` instead of `fixed`, this forces the dropdown to also align with the vertical limits of the table. I'm not sure that there is a simple solution, since I think it would require separating `Table.Dropdown` from the rest of the table so that we can conform to the width of the parent, but not the vertical limits.

Comment (ramiAbdou) [reply packages/ui/src/components/table.tsx]: Yeah I would love to use position `absolute` which is the default for our dropdown since it auto-aligns perfectly, but unfortunately the `overflow-scroll` on the table container is why the dropdown gets hidden underneath.

To recap our options:
1. Your initial solution, which fixes the issue for most of our use cases but is just a bit hard-codey.
2. We do position absolute, and introduce a different (but maybe a bit better?) usability bug of the dropdown being hidden underneath.
3. We do a fixed position, and then introduce some React/JS logic to set the `right` value. We'd have to take into account the screen size, scroll position, etc.

I'm genuinely torn b/c I'm not a huge fan of any of the options 😭 but 1 is probably my top choice considering the tradeoffs. What do you think?

I tried to find examples in the wild of tables that support 1) scrollable rows, 2) a sticky menu option on the right side of the row, and 3) dropdowns in the table, but I couldn't really find any. Maybe it's not the best design (I feel like it is though ugh)!

Comment (tomas-salgado) [reply packages/ui/src/components/table.tsx]: In response to (2), the 'bug' won't always be noticeable because when a table has enough entries (which, in prod, would be most cases), the table size will be readjusted so no scrolling will be needed to see the dropdown elements. However this is still essentially introducing a bug so that doesn't seem like a good option. 

(3) seems like it could be unnecessarily complicated since there'd be a lot of positioning considerations that could potentially introduce different bugs when used on different devices/screens, etc., and this could end up making it more complicated to make other tables in the future. 

I'm leaning towards (1) as well, because even though it is a bit hard-codey, it does fit with all the uses of tables now, and I wonder if in the future a different kind of table is needed, maybe it'd be worth creating a new table dropdown element if needed, and leave the current one as the main dropdown.

Comment (ramiAbdou) [reply packages/ui/src/components/table.tsx]: Okay let's go with option 1!

File: packages/ui/src/components/table.tsx [hunk 2]
```diff
@@ -181,7 +181,7 @@ function TableBody({
 
 Table.Dropdown = function TableDropdown({ children }: PropsWithChildren) {
   return (
-    <Dropdown className="fixed right-[unset] mt-[unset] translate-x-[calc(-100%-0.5rem)]">
+    <Dropdown className="fixed right-16 mt-[unset] md:right-20">
```
Comment (ramiAbdou) [inline packages/ui/src/components/table.tsx:184]: I tweaked this slighly to just set the `right` value instead of combining right + margin-right + translate-x!

**Review by ramiAbdou — APPROVED** [review]
